[2024-04-18 23:32:51,702: INFO: main: welcome to cnnClassifier]
[2024-04-19 09:21:10,665: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-19 09:21:10,679: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-19 09:23:00,812: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-19 09:23:00,815: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-19 09:24:49,725: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-19 09:24:49,727: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-19 09:32:08,711: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-19 09:32:08,720: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-19 09:32:08,723: INFO: common: created directory at: artifacts]
[2024-04-19 09:32:08,734: INFO: common: created directory at: artifacts/data_ingestion]
[2024-04-19 09:32:08,737: INFO: 1983665874: Downloading data from https://drive.google.com/file/d/1z0mreUtRmR-P-magILsDR3T7M6IkGXtY/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-04-19 09:32:10,564: INFO: 1983665874: Downloaded data from https://drive.google.com/file/d/1z0mreUtRmR-P-magILsDR3T7M6IkGXtY/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-04-19 09:35:26,783: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-19 09:35:26,789: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-19 09:35:26,792: INFO: common: created directory at: artifacts]
[2024-04-19 09:35:26,795: INFO: common: created directory at: artifacts/data_ingestion]
[2024-04-19 09:35:26,797: INFO: 1983665874: Downloading data from https://drive.google.com/file/d/1z0mreUtRmR-P-magILsDR3T7M6IkGXtY/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-04-19 09:35:31,222: INFO: 1983665874: Downloaded data from https://drive.google.com/file/d/1z0mreUtRmR-P-magILsDR3T7M6IkGXtY/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-04-19 10:41:48,992: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-19 10:41:48,997: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-19 10:41:48,999: INFO: common: created directory at: artifacts]
[2024-04-19 10:41:49,001: INFO: common: created directory at: artifacts/data_ingestion]
[2024-04-19 10:41:49,003: INFO: 1983665874: Downloading data from https://drive.google.com/drive/folders/1UlGQtGlo7ygK3Jsal4CXRs-YBXM98Vrs?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-04-19 10:41:49,708: INFO: 1983665874: Downloaded data from https://drive.google.com/drive/folders/1UlGQtGlo7ygK3Jsal4CXRs-YBXM98Vrs?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-04-19 10:50:31,740: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-19 10:50:31,747: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-19 10:50:31,749: INFO: common: created directory at: artifacts]
[2024-04-19 10:50:31,752: INFO: common: created directory at: artifacts/data_ingestion]
[2024-04-19 10:50:31,755: INFO: 1983665874: Downloading data from https://drive.google.com/drive/folders/1UlGQtGlo7ygK3Jsal4CXRs-YBXM98Vrs?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-04-19 10:50:32,383: INFO: 1983665874: Downloaded data from https://drive.google.com/drive/folders/1UlGQtGlo7ygK3Jsal4CXRs-YBXM98Vrs?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-04-19 10:53:15,935: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-19 10:53:15,940: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-19 10:53:15,941: INFO: common: created directory at: artifacts]
[2024-04-19 10:53:15,943: INFO: common: created directory at: artifacts/data_ingestion]
[2024-04-19 10:53:15,944: INFO: 1983665874: Downloading data from https://drive.google.com/drive/folders/1UlGQtGlo7ygK3Jsal4CXRs-YBXM98Vrs?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-04-19 10:53:16,556: INFO: 1983665874: Downloaded data from https://drive.google.com/drive/folders/1UlGQtGlo7ygK3Jsal4CXRs-YBXM98Vrs?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-04-19 14:12:28,771: INFO: main: >>>>>> stage Data Ingestion Stage started <<<<<<]
[2024-04-19 14:12:28,828: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-19 14:12:28,834: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-19 14:12:28,835: INFO: common: created directory at: artifacts]
[2024-04-19 14:12:28,837: INFO: common: created directory at: artifacts/data_ingestion]
[2024-04-19 14:12:28,837: INFO: data_ingestion: Downloading data from https://drive.google.com/drive/folders/1UlGQtGlo7ygK3Jsal4CXRs-YBXM98Vrs?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-04-19 14:12:29,921: INFO: data_ingestion: Downloaded data from https://drive.google.com/drive/folders/1UlGQtGlo7ygK3Jsal4CXRs-YBXM98Vrs?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-04-19 14:12:29,921: ERROR: main: [Errno 2] No such file or directory: 'artifacts/data_ingestion/data.zip']
Traceback (most recent call last):
  File "main.py", line 9, in <module>
    obj.main()
  File "D:\Data science\MLOPS\END-TO-END-Chest-cancer-classification-using-mlflows\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 16, in main
    data_ingestion.extract_zip_file()
  File "D:\Data science\MLOPS\END-TO-END-Chest-cancer-classification-using-mlflows\src\cnnClassifier\components\data_ingestion.py", line 44, in extract_zip_file
    with zipfile.ZipFile(self.config.local_data_file, 'r') as zip_ref:
  File "C:\Users\Hp\anaconda3\envs\kidney\lib\zipfile.py", line 1216, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: 'artifacts/data_ingestion/data.zip'
[2024-04-19 14:12:55,091: INFO: main: >>>>>> stage Data Ingestion Stage started <<<<<<]
[2024-04-19 14:12:55,093: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-19 14:12:55,096: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-19 14:12:55,097: INFO: common: created directory at: artifacts]
[2024-04-19 14:12:55,098: INFO: common: created directory at: artifacts/data_ingestion]
[2024-04-19 14:12:55,098: INFO: data_ingestion: Downloading data from https://drive.google.com/drive/folders/1UlGQtGlo7ygK3Jsal4CXRs-YBXM98Vrs?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-04-19 14:12:56,016: INFO: data_ingestion: Downloaded data from https://drive.google.com/drive/folders/1UlGQtGlo7ygK3Jsal4CXRs-YBXM98Vrs?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-04-19 14:12:57,325: INFO: main: >>>>>> stage Data Ingestion Stage completed <<<<<<

x==========x]
[2024-04-19 14:38:48,071: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-19 14:38:48,128: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-19 14:38:48,142: INFO: common: created directory at: artifacts]
[2024-04-19 14:38:48,171: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-04-19 14:38:50,957: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-04-19 14:50:50,350: INFO: main: >>>>>> stage Data Ingestion Stage started <<<<<<]
[2024-04-19 14:50:50,356: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-19 14:50:50,360: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-19 14:50:50,361: INFO: common: created directory at: artifacts]
[2024-04-19 14:50:50,363: INFO: common: created directory at: artifacts/data_ingestion]
[2024-04-19 14:50:50,363: INFO: data_ingestion: Downloading data from https://drive.google.com/drive/folders/1UlGQtGlo7ygK3Jsal4CXRs-YBXM98Vrs?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-04-19 14:50:51,237: INFO: data_ingestion: Downloaded data from https://drive.google.com/drive/folders/1UlGQtGlo7ygK3Jsal4CXRs-YBXM98Vrs?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-04-19 14:50:51,264: ERROR: main: [Errno 2] No such file or directory: 'artifacts/data_ingestion/data.zip']
Traceback (most recent call last):
  File "main.py", line 10, in <module>
    obj.main()
  File "D:\Data science\MLOPS\END-TO-END-Chest-cancer-classification-using-mlflows\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 16, in main
    data_ingestion.extract_zip_file()
  File "D:\Data science\MLOPS\END-TO-END-Chest-cancer-classification-using-mlflows\src\cnnClassifier\components\data_ingestion.py", line 44, in extract_zip_file
    with zipfile.ZipFile(self.config.local_data_file, 'r') as zip_ref:
  File "C:\Users\Hp\anaconda3\envs\kidney\lib\zipfile.py", line 1216, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: 'artifacts/data_ingestion/data.zip'
[2024-04-19 14:51:44,566: INFO: main: *******************]
[2024-04-19 14:51:44,568: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-04-19 14:51:44,578: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-19 14:51:44,584: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-19 14:51:44,585: INFO: common: created directory at: artifacts]
[2024-04-19 14:51:44,612: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-04-19 14:51:45,834: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-04-19 14:51:48,274: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-04-19 15:03:33,847: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-19 15:03:33,882: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-19 15:03:33,887: INFO: common: created directory at: artifacts]
[2024-04-19 15:03:33,904: INFO: common: created directory at: artifacts\training]
[2024-04-19 15:12:16,362: INFO: main: *******************]
[2024-04-19 15:12:16,382: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-04-19 15:12:16,390: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-19 15:12:16,400: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-19 15:12:16,412: INFO: common: created directory at: artifacts]
[2024-04-19 15:12:16,426: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-04-19 15:12:17,567: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-04-19 15:12:18,856: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-04-19 15:12:18,857: INFO: main: *******************]
[2024-04-19 15:12:18,857: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-04-19 15:12:18,863: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-19 15:12:18,868: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-19 15:12:18,869: INFO: common: created directory at: artifacts]
[2024-04-19 15:12:18,870: INFO: common: created directory at: artifacts\training]
[2024-04-19 15:14:15,026: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-04-19 15:41:15,183: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-19 15:41:15,265: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-19 15:41:15,289: INFO: common: created directory at: artifacts]
[2024-04-19 15:41:55,931: INFO: common: json file saved at: scores.json]
[2024-04-19 15:41:57,649: WARNING: connectionpool: Retrying (Retry(total=4, connect=4, read=5, redirect=5, status=5)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001CAC38748B0>: Failed to resolve 'dagshub.com' ([Errno 11001] getaddrinfo failed)")': /Prajwal07523/END-TO-END-Chest-cancer-classification-using-mlflows.mlflow/api/2.0/mlflow/runs/create]
[2024-04-19 15:42:01,664: WARNING: connectionpool: Retrying (Retry(total=3, connect=3, read=5, redirect=5, status=5)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001CAC3874880>: Failed to resolve 'dagshub.com' ([Errno 11001] getaddrinfo failed)")': /Prajwal07523/END-TO-END-Chest-cancer-classification-using-mlflows.mlflow/api/2.0/mlflow/runs/create]
[2024-04-19 15:42:09,682: WARNING: connectionpool: Retrying (Retry(total=2, connect=2, read=5, redirect=5, status=5)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001CAC3874FD0>: Failed to resolve 'dagshub.com' ([Errno 11001] getaddrinfo failed)")': /Prajwal07523/END-TO-END-Chest-cancer-classification-using-mlflows.mlflow/api/2.0/mlflow/runs/create]
[2024-04-19 15:42:25,689: WARNING: connectionpool: Retrying (Retry(total=1, connect=1, read=5, redirect=5, status=5)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001CAC3874DF0>: Failed to resolve 'dagshub.com' ([Errno 11001] getaddrinfo failed)")': /Prajwal07523/END-TO-END-Chest-cancer-classification-using-mlflows.mlflow/api/2.0/mlflow/runs/create]
[2024-04-19 15:42:57,701: WARNING: connectionpool: Retrying (Retry(total=0, connect=0, read=5, redirect=5, status=5)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001CAC386F250>: Failed to resolve 'dagshub.com' ([Errno 11001] getaddrinfo failed)")': /Prajwal07523/END-TO-END-Chest-cancer-classification-using-mlflows.mlflow/api/2.0/mlflow/runs/create]
[2024-04-19 15:43:29,006: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-19 15:43:29,024: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-19 15:43:29,031: INFO: common: created directory at: artifacts]
[2024-04-19 15:44:02,064: INFO: common: json file saved at: scores.json]
[2024-04-19 15:44:08,564: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-04-19 15:46:18,414: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-19 15:46:18,424: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-19 15:46:18,428: INFO: common: created directory at: artifacts]
[2024-04-19 15:46:41,084: INFO: common: json file saved at: scores.json]
[2024-04-19 15:46:47,008: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-04-19 16:15:44,630: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-19 16:15:44,933: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-19 16:15:44,935: INFO: common: created directory at: artifacts]
[2024-04-19 16:16:08,775: INFO: common: json file saved at: scores.json]
[2024-04-19 16:16:14,405: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-04-19 16:16:15,655: INFO: builder_impl: Assets written to: C:\Users\Hp\AppData\Local\Temp\tmpdxa_6k27\model\data\model\assets]
[2024-04-19 16:43:07,146: INFO: main: *******************]
[2024-04-19 16:43:07,187: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-04-19 16:43:07,206: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-19 16:43:07,213: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-19 16:43:07,215: INFO: common: created directory at: artifacts]
[2024-04-19 16:43:44,186: INFO: common: json file saved at: scores.json]
[2024-04-19 16:43:44,192: INFO: common: json file saved at: scores.json]
[2024-04-19 16:43:44,193: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-04-19 16:45:16,899: INFO: main: *******************]
[2024-04-19 16:45:16,899: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-04-19 16:45:16,902: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-19 16:45:16,915: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-19 16:45:16,915: INFO: common: created directory at: artifacts]
[2024-04-19 16:45:16,915: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-04-19 16:45:18,110: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-04-19 16:45:18,900: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-04-19 16:45:18,908: INFO: main: *******************]
[2024-04-19 16:45:18,908: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-04-19 16:45:18,912: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-19 16:45:18,919: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-19 16:45:18,920: INFO: common: created directory at: artifacts]
[2024-04-19 16:45:18,920: INFO: common: created directory at: artifacts\training]
[2024-04-19 16:47:03,514: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-04-19 16:47:03,519: INFO: main: *******************]
[2024-04-19 16:47:03,519: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-04-19 16:47:03,526: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-19 16:47:03,530: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-19 16:47:03,530: INFO: common: created directory at: artifacts]
[2024-04-19 16:47:34,470: INFO: common: json file saved at: scores.json]
[2024-04-19 16:47:34,470: INFO: common: json file saved at: scores.json]
[2024-04-19 16:47:34,470: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-04-19 16:49:47,771: INFO: main: *******************]
[2024-04-19 16:49:47,771: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-04-19 16:49:47,781: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-19 16:49:47,781: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-19 16:49:47,785: INFO: common: created directory at: artifacts]
[2024-04-19 16:49:47,785: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-04-19 16:49:48,453: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-04-19 16:49:48,804: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-04-19 16:49:48,804: INFO: main: *******************]
[2024-04-19 16:49:48,804: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-04-19 16:49:48,813: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-19 16:49:48,820: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-19 16:49:48,820: INFO: common: created directory at: artifacts]
[2024-04-19 16:49:48,820: INFO: common: created directory at: artifacts\training]
[2024-04-19 16:51:33,309: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-04-19 16:51:33,318: INFO: main: *******************]
[2024-04-19 16:51:33,318: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-04-19 16:51:33,324: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-19 16:51:33,324: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-19 16:51:33,334: INFO: common: created directory at: artifacts]
[2024-04-19 16:52:09,605: INFO: common: json file saved at: scores.json]
[2024-04-19 16:52:09,605: INFO: common: json file saved at: scores.json]
[2024-04-19 16:52:18,210: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-04-19 16:52:20,360: INFO: builder_impl: Assets written to: C:\Users\Hp\AppData\Local\Temp\tmp4qhtifrb\model\data\model\assets]
[2024-04-20 00:17:56,630: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://10.7.2.145:8080]
[2024-04-20 00:17:56,642: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-04-20 00:19:26,951: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8000
 * Running on http://10.7.2.145:8000]
[2024-04-20 00:19:26,952: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-04-20 00:19:52,042: INFO: _internal: 127.0.0.1 - - [20/Apr/2024 00:19:52] "GET / HTTP/1.1" 200 -]
[2024-04-20 00:20:07,298: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\Hp\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Hp\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Hp\anaconda3\envs\kidney\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\Hp\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Hp\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\Hp\anaconda3\envs\kidney\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "app.py", line 46, in predictRoute
    result = clApp.classifier.predict()
  File "D:\Data science\MLOPS\END-TO-END-Chest-cancer-classification-using-mlflows\src\cnnClassifier\pipeline\prediction.py", line 18, in predict
    model = load_model(os.path.join("model", "model.h5"))
  File "C:\Users\Hp\anaconda3\envs\kidney\lib\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
  File "C:\Users\Hp\anaconda3\envs\kidney\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\Hp\anaconda3\envs\kidney\lib\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at model\model.h5
[2024-04-20 00:20:07,335: INFO: _internal: 127.0.0.1 - - [20/Apr/2024 00:20:07] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-04-20 00:21:26,678: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8000
 * Running on http://10.7.2.145:8000]
[2024-04-20 00:21:26,679: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-04-20 00:21:34,901: INFO: _internal: 127.0.0.1 - - [20/Apr/2024 00:21:34] "GET / HTTP/1.1" 200 -]
[2024-04-20 00:21:41,480: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\Hp\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Hp\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Hp\anaconda3\envs\kidney\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\Hp\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Hp\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\Hp\anaconda3\envs\kidney\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "app.py", line 46, in predictRoute
    result = clApp.classifier.predict()
  File "D:\Data science\MLOPS\END-TO-END-Chest-cancer-classification-using-mlflows\src\cnnClassifier\pipeline\prediction.py", line 18, in predict
    model = load_model(os.path.join("model", "model.h5"))
  File "C:\Users\Hp\anaconda3\envs\kidney\lib\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
  File "C:\Users\Hp\anaconda3\envs\kidney\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\Hp\anaconda3\envs\kidney\lib\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at model\model.h5
[2024-04-20 00:21:41,545: INFO: _internal: 127.0.0.1 - - [20/Apr/2024 00:21:41] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-04-20 00:24:29,272: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8000
 * Running on http://10.7.2.145:8000]
[2024-04-20 00:24:29,273: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-04-20 00:24:38,896: INFO: _internal: 127.0.0.1 - - [20/Apr/2024 00:24:38] "GET / HTTP/1.1" 200 -]
[2024-04-20 00:24:47,926: INFO: _internal: 127.0.0.1 - - [20/Apr/2024 00:24:47] "POST /predict HTTP/1.1" 200 -]
[2024-04-20 00:25:08,382: INFO: _internal: 127.0.0.1 - - [20/Apr/2024 00:25:08] "POST /predict HTTP/1.1" 200 -]
[2024-04-20 00:25:12,939: INFO: _internal: 127.0.0.1 - - [20/Apr/2024 00:25:12] "POST /predict HTTP/1.1" 200 -]
[2024-04-20 00:25:24,360: INFO: _internal: 127.0.0.1 - - [20/Apr/2024 00:25:24] "POST /predict HTTP/1.1" 200 -]
[2024-04-20 00:25:31,906: INFO: _internal: 127.0.0.1 - - [20/Apr/2024 00:25:31] "GET / HTTP/1.1" 200 -]
[2024-04-20 00:25:46,343: WARNING: polymorphic_function: 5 out of the last 5 calls to <function Model.make_predict_function.<locals>.predict_function at 0x000001D0DB5EF280> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2024-04-20 00:25:46,350: INFO: _internal: 127.0.0.1 - - [20/Apr/2024 00:25:46] "POST /predict HTTP/1.1" 200 -]
[2024-04-20 00:25:59,555: WARNING: polymorphic_function: 6 out of the last 6 calls to <function Model.make_predict_function.<locals>.predict_function at 0x000001D0DCEAC940> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2024-04-20 00:25:59,564: INFO: _internal: 127.0.0.1 - - [20/Apr/2024 00:25:59] "POST /predict HTTP/1.1" 200 -]
[2024-04-22 12:55:17,522: INFO: main: >>>>>> stage Data Ingestion Stage started <<<<<<]
[2024-04-22 12:55:17,527: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-22 12:55:17,536: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-22 12:55:17,537: INFO: common: created directory at: artifacts]
[2024-04-22 12:55:17,538: INFO: common: created directory at: artifacts/data_ingestion]
[2024-04-22 12:55:17,540: INFO: data_ingestion: Downloading data from https://drive.google.com/drive/folders/1UlGQtGlo7ygK3Jsal4CXRs-YBXM98Vrs?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-04-22 12:55:18,153: INFO: data_ingestion: Downloaded data from https://drive.google.com/drive/folders/1UlGQtGlo7ygK3Jsal4CXRs-YBXM98Vrs?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-04-22 12:55:18,155: ERROR: main: [Errno 2] No such file or directory: 'artifacts/data_ingestion/data.zip']
Traceback (most recent call last):
  File "main.py", line 14, in <module>
    obj.main()
  File "D:\Data science\MLOPS\END-TO-END-Chest-cancer-classification-using-mlflows\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 16, in main
    data_ingestion.extract_zip_file()
  File "D:\Data science\MLOPS\END-TO-END-Chest-cancer-classification-using-mlflows\src\cnnClassifier\components\data_ingestion.py", line 44, in extract_zip_file
    with zipfile.ZipFile(self.config.local_data_file, 'r') as zip_ref:
  File "C:\Users\Hp\anaconda3\envs\kidney\lib\zipfile.py", line 1216, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: 'artifacts/data_ingestion/data.zip'
[2024-04-22 12:57:06,746: INFO: main: >>>>>> stage Data Ingestion Stage started <<<<<<]
[2024-04-22 12:57:06,791: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-22 12:57:06,796: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-22 12:57:06,797: INFO: common: created directory at: artifacts]
[2024-04-22 12:57:06,798: INFO: common: created directory at: artifacts/data_ingestion]
[2024-04-22 12:57:06,798: INFO: data_ingestion: Downloading data from https://drive.google.com/drive/folders/1UlGQtGlo7ygK3Jsal4CXRs-YBXM98Vrs?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-04-22 12:57:07,232: INFO: data_ingestion: Downloaded data from https://drive.google.com/drive/folders/1UlGQtGlo7ygK3Jsal4CXRs-YBXM98Vrs?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-04-22 12:57:08,908: INFO: main: >>>>>> stage Data Ingestion Stage completed <<<<<<

x==========x]
[2024-04-22 12:57:08,910: INFO: main: *******************]
[2024-04-22 12:57:08,910: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-04-22 12:57:08,916: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-22 12:57:08,918: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-22 12:57:08,919: INFO: common: created directory at: artifacts]
[2024-04-22 12:57:08,920: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-04-22 12:57:10,306: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-04-22 12:57:12,022: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-04-22 12:57:12,023: INFO: main: *******************]
[2024-04-22 12:57:12,023: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-04-22 12:57:12,029: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-22 12:57:12,034: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-22 12:57:12,133: INFO: common: created directory at: artifacts]
[2024-04-22 12:57:12,134: INFO: common: created directory at: artifacts\training]
[2024-04-22 12:57:13,501: ERROR: main: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\Chest-CT-Scan-data']
Traceback (most recent call last):
  File "main.py", line 36, in <module>
    model_trainer.main()
  File "D:\Data science\MLOPS\END-TO-END-Chest-cancer-classification-using-mlflows\src\cnnClassifier\pipeline\stage_03_model_trainer.py", line 20, in main
    training.train_valid_generator()
  File "d:\data science\mlops\end-to-end-chest-cancer-classification-using-mlflows\src\cnnClassifier\components\model_trainer.py", line 38, in train_valid_generator
    self.valid_generator = valid_datagenerator.flow_from_directory(
  File "C:\Users\Hp\anaconda3\envs\kidney\lib\site-packages\keras\preprocessing\image.py", line 1648, in flow_from_directory
    return DirectoryIterator(
  File "C:\Users\Hp\anaconda3\envs\kidney\lib\site-packages\keras\preprocessing\image.py", line 563, in __init__
    for subdir in sorted(os.listdir(directory)):
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\Chest-CT-Scan-data'
[2024-04-22 12:58:21,960: INFO: main: >>>>>> stage Data Ingestion Stage started <<<<<<]
[2024-04-22 12:58:22,007: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-22 12:58:22,013: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-22 12:58:22,015: INFO: common: created directory at: artifacts]
[2024-04-22 12:58:22,015: INFO: common: created directory at: artifacts/data_ingestion]
[2024-04-22 12:58:22,016: INFO: data_ingestion: Downloading data from https://drive.google.com/drive/folders/1UlGQtGlo7ygK3Jsal4CXRs-YBXM98Vrs?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-04-22 12:58:22,475: INFO: data_ingestion: Downloaded data from https://drive.google.com/drive/folders/1UlGQtGlo7ygK3Jsal4CXRs-YBXM98Vrs?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-04-22 12:58:24,338: INFO: main: >>>>>> stage Data Ingestion Stage completed <<<<<<

x==========x]
[2024-04-22 12:58:24,338: INFO: main: *******************]
[2024-04-22 12:58:24,338: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-04-22 12:58:24,347: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-22 12:58:24,353: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-22 12:58:24,355: INFO: common: created directory at: artifacts]
[2024-04-22 12:58:24,356: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-04-22 12:58:25,743: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-04-22 12:58:28,465: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-04-22 12:58:28,465: INFO: main: *******************]
[2024-04-22 12:58:28,467: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-04-22 12:58:28,474: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-22 12:58:28,480: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-22 12:58:28,482: INFO: common: created directory at: artifacts]
[2024-04-22 12:58:28,483: INFO: common: created directory at: artifacts\training]
[2024-04-22 13:00:37,483: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-04-22 13:00:37,490: INFO: main: *******************]
[2024-04-22 13:00:37,490: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-04-22 13:00:37,523: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-22 13:00:37,536: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-22 13:00:37,540: INFO: common: created directory at: artifacts]
[2024-04-22 13:01:21,040: INFO: common: json file saved at: scores.json]
[2024-04-22 13:01:21,046: INFO: common: json file saved at: scores.json]
[2024-04-22 13:01:30,790: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-04-22 13:01:33,619: INFO: builder_impl: Assets written to: C:\Users\Hp\AppData\Local\Temp\tmpwa8medt7\model\data\model\assets]
[2024-04-22 13:02:02,420: INFO: dir_util: creating D:\Data science\MLOPS\END-TO-END-Chest-cancer-classification-using-mlflows\mlruns\0\e16bb6492b274755a6e07d8828fa19e4\artifacts\model\data]
[2024-04-22 13:02:02,581: INFO: dir_util: creating D:\Data science\MLOPS\END-TO-END-Chest-cancer-classification-using-mlflows\mlruns\0\e16bb6492b274755a6e07d8828fa19e4\artifacts\model\data\model]
[2024-04-22 13:02:02,584: INFO: dir_util: creating D:\Data science\MLOPS\END-TO-END-Chest-cancer-classification-using-mlflows\mlruns\0\e16bb6492b274755a6e07d8828fa19e4\artifacts\model\data\model\assets]
[2024-04-22 13:02:02,648: INFO: dir_util: creating D:\Data science\MLOPS\END-TO-END-Chest-cancer-classification-using-mlflows\mlruns\0\e16bb6492b274755a6e07d8828fa19e4\artifacts\model\data\model\variables]
[2024-04-22 13:02:02,954: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-04-22 13:11:40,774: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-22 13:11:40,823: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-22 13:11:40,825: INFO: common: created directory at: artifacts]
[2024-04-22 13:12:06,828: INFO: common: json file saved at: scores.json]
[2024-04-22 13:12:11,942: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-04-22 13:12:13,118: INFO: builder_impl: Assets written to: C:\Users\Hp\AppData\Local\Temp\tmplcaiu8th\model\data\model\assets]
[2024-04-22 13:24:38,483: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-22 13:24:38,535: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-22 13:24:38,537: INFO: common: created directory at: artifacts]
[2024-04-22 13:25:03,584: INFO: common: json file saved at: scores.json]
[2024-04-22 13:25:14,905: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-04-22 13:25:16,488: INFO: builder_impl: Assets written to: C:\Users\Hp\AppData\Local\Temp\tmpumlhz_ef\model\data\model\assets]
[2024-04-22 13:46:01,672: INFO: main: >>>>>> stage Data Ingestion Stage started <<<<<<]
[2024-04-22 13:46:01,680: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-22 13:46:01,685: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-22 13:46:01,686: INFO: common: created directory at: artifacts]
[2024-04-22 13:46:01,687: INFO: common: created directory at: artifacts/data_ingestion]
[2024-04-22 13:46:01,688: INFO: data_ingestion: Downloading data from https://drive.google.com/drive/folders/1UlGQtGlo7ygK3Jsal4CXRs-YBXM98Vrs?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-04-22 13:46:02,111: INFO: data_ingestion: Downloaded data from https://drive.google.com/drive/folders/1UlGQtGlo7ygK3Jsal4CXRs-YBXM98Vrs?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-04-22 13:46:04,206: INFO: main: >>>>>> stage Data Ingestion Stage completed <<<<<<

x==========x]
[2024-04-22 13:46:04,208: INFO: main: *******************]
[2024-04-22 13:46:04,209: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-04-22 13:46:04,213: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-22 13:46:04,218: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-22 13:46:04,220: INFO: common: created directory at: artifacts]
[2024-04-22 13:46:04,221: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-04-22 13:46:05,589: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-04-22 13:46:07,733: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-04-22 13:46:07,734: INFO: main: *******************]
[2024-04-22 13:46:07,735: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-04-22 13:46:07,740: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-22 13:46:07,743: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-22 13:46:07,745: INFO: common: created directory at: artifacts]
[2024-04-22 13:46:07,763: INFO: common: created directory at: artifacts\training]
[2024-04-22 13:47:29,046: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-04-22 13:47:29,048: INFO: main: *******************]
[2024-04-22 13:47:29,048: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-04-22 13:47:29,058: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-22 13:47:29,061: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-22 13:47:29,063: INFO: common: created directory at: artifacts]
[2024-04-22 13:47:59,630: INFO: common: json file saved at: scores.json]
[2024-04-22 13:47:59,635: INFO: common: json file saved at: scores.json]
[2024-04-22 13:48:04,651: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-04-22 13:48:05,763: INFO: builder_impl: Assets written to: C:\Users\Hp\AppData\Local\Temp\tmpz_gj8cll\model\data\model\assets]
[2024-04-22 13:48:16,432: INFO: dir_util: creating D:\Data science\MLOPS\END-TO-END-Chest-cancer-classification-using-mlflows\mlruns\0\a00404d04b484dd7909a952bde1fdf87\artifacts\model\data]
[2024-04-22 13:48:16,435: INFO: dir_util: creating D:\Data science\MLOPS\END-TO-END-Chest-cancer-classification-using-mlflows\mlruns\0\a00404d04b484dd7909a952bde1fdf87\artifacts\model\data\model]
[2024-04-22 13:48:16,438: INFO: dir_util: creating D:\Data science\MLOPS\END-TO-END-Chest-cancer-classification-using-mlflows\mlruns\0\a00404d04b484dd7909a952bde1fdf87\artifacts\model\data\model\assets]
[2024-04-22 13:48:16,449: INFO: dir_util: creating D:\Data science\MLOPS\END-TO-END-Chest-cancer-classification-using-mlflows\mlruns\0\a00404d04b484dd7909a952bde1fdf87\artifacts\model\data\model\variables]
[2024-04-22 13:48:16,616: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-04-22 14:15:06,713: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion Stage started <<<<<<]
[2024-04-22 14:15:06,717: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-22 14:15:06,722: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-22 14:15:06,723: INFO: common: created directory at: artifacts]
[2024-04-22 14:15:06,723: INFO: common: created directory at: artifacts/data_ingestion]
[2024-04-22 14:15:06,724: INFO: data_ingestion: Downloading data from https://drive.google.com/drive/folders/1UlGQtGlo7ygK3Jsal4CXRs-YBXM98Vrs?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-04-22 14:15:07,161: INFO: data_ingestion: Downloaded data from https://drive.google.com/drive/folders/1UlGQtGlo7ygK3Jsal4CXRs-YBXM98Vrs?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-04-22 14:15:10,605: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion Stage completed <<<<<<

x==========x]
[2024-04-22 14:16:14,576: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion Stage started <<<<<<]
[2024-04-22 14:16:14,582: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-22 14:16:14,585: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-22 14:16:14,585: INFO: common: created directory at: artifacts]
[2024-04-22 14:16:14,586: INFO: common: created directory at: artifacts/data_ingestion]
[2024-04-22 14:16:14,587: INFO: data_ingestion: Downloading data from https://drive.google.com/drive/folders/1UlGQtGlo7ygK3Jsal4CXRs-YBXM98Vrs?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-04-22 14:16:15,038: INFO: data_ingestion: Downloaded data from https://drive.google.com/drive/folders/1UlGQtGlo7ygK3Jsal4CXRs-YBXM98Vrs?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-04-22 14:16:16,516: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion Stage completed <<<<<<

x==========x]
[2024-04-22 14:17:11,521: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion Stage started <<<<<<]
[2024-04-22 14:17:11,524: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-22 14:17:11,528: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-22 14:17:11,528: INFO: common: created directory at: artifacts]
[2024-04-22 14:17:11,529: INFO: common: created directory at: artifacts/data_ingestion]
[2024-04-22 14:17:11,529: INFO: data_ingestion: Downloading data from https://drive.google.com/drive/folders/1UlGQtGlo7ygK3Jsal4CXRs-YBXM98Vrs?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-04-22 14:17:11,937: INFO: data_ingestion: Downloaded data from https://drive.google.com/drive/folders/1UlGQtGlo7ygK3Jsal4CXRs-YBXM98Vrs?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-04-22 14:17:13,076: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion Stage completed <<<<<<

x==========x]
[2024-04-22 14:18:49,988: INFO: stage_02_prepare_base_model: *******************]
[2024-04-22 14:18:49,989: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare base model started <<<<<<]
[2024-04-22 14:18:49,995: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-22 14:18:50,006: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-22 14:18:50,010: INFO: common: created directory at: artifacts]
[2024-04-22 14:18:50,020: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-04-22 14:18:51,348: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-04-22 14:18:53,395: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-04-22 14:19:08,230: INFO: stage_03_model_trainer: *******************]
[2024-04-22 14:19:08,230: INFO: stage_03_model_trainer: >>>>>> stage Training started <<<<<<]
[2024-04-22 14:19:08,235: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-22 14:19:08,238: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-22 14:19:08,239: INFO: common: created directory at: artifacts]
[2024-04-22 14:19:08,239: INFO: common: created directory at: artifacts\training]
[2024-04-22 14:20:28,303: INFO: stage_03_model_trainer: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-04-22 14:20:40,332: INFO: stage_04_model_evaluation: *******************]
[2024-04-22 14:20:40,333: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage started <<<<<<]
[2024-04-22 14:20:40,339: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-22 14:20:40,344: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-22 14:20:40,345: INFO: common: created directory at: artifacts]
[2024-04-22 14:21:05,881: INFO: common: json file saved at: scores.json]
[2024-04-22 14:21:05,883: INFO: common: json file saved at: scores.json]
[2024-04-22 14:21:05,884: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
